export const CLICK = 'CLICK';

export const {
  GET_PEOPLE, GET_PEOPLE_START, GET_PEOPLE_SECCESS, GET_PEOPLE_FAILURE,
} = {
  GET_PEOPLE: 'GET_PEOPLE',
  GET_PEOPLE_START: 'GET_PEOPLE_START',
  GET_PEOPLE_SECCESS: 'GET_PEOPLE_SECCESS',
  GET_PEOPLE_FAILURE: 'GET_PEOPLE_FAILURE',
};

export const {
  GET_PLANETS, GET_PLANETS_START, GET_PLANETS_SECCESS, GET_PLANETS_FAILURE,
} = {
  GET_PLANETS: 'GET_PLANETS',
  GET_PLANETS_START: 'GET_PLANETS_START',
  GET_PLANETS_SECCESS: 'GET_PLANETS_SECCESS',
  GET_PLANETS_FAILURE: 'GET_PLANETS_FAILURE',
};
